# Generated by Django 4.0.4 on 2022-05-12 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.IntegerField(default=0)),
                ('member_type', models.CharField(default='', max_length=2)),
                ('name', models.CharField(default='', max_length=300)),
                ('sex', models.CharField(default='', max_length=3)),
                ('father_husband_name', models.CharField(default='', max_length=300)),
                ('house_name', models.CharField(default='', max_length=700)),
                ('kara', models.CharField(default='', max_length=700)),
                ('post', models.CharField(default='', max_length=300)),
                ('pin', models.CharField(default='', max_length=300)),
                ('village', models.CharField(default='', max_length=300)),
                ('taluk', models.CharField(default='', max_length=300)),
                ('panchayath', models.CharField(default='', max_length=300)),
                ('ward', models.CharField(default='', max_length=300)),
                ('mobile_number', models.CharField(default='', max_length=300)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('age', models.IntegerField(default=0)),
                ('aadhar', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
