# Generated by Django 4.0.4 on 2022-05-13 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_alter_memberdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetails',
            name='aadhar',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='dob',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='father_husband_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='house_name',
            field=models.CharField(default='', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='kara',
            field=models.CharField(default='', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='member_type',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='mobile_number',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='name',
            field=models.CharField(default='', max_length=301, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='panchayath',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='pin',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='post',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='sex',
            field=models.CharField(default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='taluk',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='village',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='ward',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
